export const ActionTypes = {
    LOAD_BOARD: 'LOAD_BOARD',
    LOAD_BOARDS: 'LOAD_BOARDS',
    ADD_BOARD: 'ADD_BOARD',
    ADD_BOARD_USER: 'ADD_BOARD_USER'
}

export const EventTypes = {
    LOAD_BOARD_COMPLETED: 'LOAD_BOARD_COMPLETED',
    LOAD_BOARDS_COMPLETED: 'LOAD_BOARDS_COMPLETED',
    ADD_BOARD_USER_COMPLETED: 'ADD_BOARD_USER_COMPLETED'
}

export default ActionTypes;