export const ActionTypes = {
    LOAD_ISSUES: 'LOAD_ISSUES',
    SAVE_ISSUE: 'SAVE_ISSUE',
    DELETE_ISSUE: 'DELETE_ISSUE',
    BULKUPDATE_ISSUE: 'BULKUPDATE_ISSUE'
}

export const EventTypes = {
    LOAD_ISSUES_COMPLETED: 'LOAD_ISSUES_COMPLETED',
    SAVE_ISSUE_COMPLETED: 'SAVE_ISSUE_COMPLETED',
    DELETE_ISSUE_COMPLETED: 'DELETE_ISSUE_COMPLETED',
    BULKUPDATE_ISSUE_COMPLETED: 'BULKUPDATE_ISSUE_COMPLETED'
}

export default ActionTypes;